project:
  type: website


website:
  title: "Gregory Ditzler"
  navbar:
    right:
      - href: index.qmd
        text: Home
        icon: fa-home
      - href: about.qmd
        text: About
      - publications.qmd
      - group.qmd
      - funding.qmd
      - teaching.qmd
      - work.qmd
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Gregory Ditzler. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/gditzler/
      - icon: envelope
        href: mailto:ditzler@rowan.edu
      - icon: book
        href: https://scholar.google.com/citations?user=diET1AsAAAAJ&hl=en
      - icon: easel2
        href: https://speakerdeck.com/gditzler
      - icon: mortarboard
        href: https://www.rowan.edu/

format:
  html:
    theme: 
      light: simplex
      dark: [simplex, theme-dark.scss]
    css: styles.css
    toc: true
    smooth-scroll: true

editor: visual

